# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4044bc7992c6a74612dd8e739e4aed160bb90ee618077feb7072b77f5f927c3e043d0289bc8f31b5bd8f3155e1b9a32bd55b83cd1dc0da7fb5017ab8b47851bf

test:
  secret_key_base: 2b7d8c9517c748fe8bee2c733bbc61631184d60b27739a88bc3d91fae024010a3f053cac2a26745d3e37d870c8f352f005b1b6d412a6049f7d277b53909a2c11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
